const styles = {
  navbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0073e6',
    padding: '10px 20px',
    borderRadius: '8px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    fontFamily: 'Arial, sans-serif',
    '& input[type="text"]': {
      padding: '8px 12px',
      border: '1px solid #ccc',
      borderRadius: '4px',
      fontSize: '1em',
      marginRight: '10px',
      width: '200px',
      '&::placeholder': {
        color: '#888',
        fontStyle: 'italic',
      },
    },
    '& button[type="submit"], & .trackLocation button': {
      padding: '8px 12px',
      backgroundColor: '#004a99',
      color: 'white',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
      fontSize: '1em',
      marginRight: '10px',
      transition: 'background-color 0.2s ease',
      '&:hover': {
        backgroundColor: '#003366',
      },
    },
  },
  greenButton: {
    backgroundColor: '#009933',
    marginTop: '5px',
    '&:hover': {
      backgroundColor: '#007a29',
    },
  },
  trackLocation: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    marginLeft: '20px',
    '& p': {
      margin: '5px 0',
      fontSize: '0.9em',
      '&[style="color: red;"]': {
        color: '#ff3333',
        fontWeight: 'bold',
      },
    },
  },
  container: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '20px',
    padding: '20px',
    justifyContent: 'center',
  },
  forecastItem: {
    backgroundColor: '#f9f9f9',
    border: '1px solid #ddd',
    borderRadius: '8px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    padding: '20px',
    maxWidth: '200px',
    width: '100%',
    textAlign: 'center',
    transition: 'transform 0.2s',
    '&:hover': {
      transform: 'translateY(-5px)',
    },
    '& h3': {
      margin: 0,
      fontSize: '1.2em',
      color: '#333',
      borderBottom: '1px solid #ddd',
      paddingBottom: '10px',
    },
    '& p': {
      margin: '8px 0',
      fontSize: '0.95em',
      color: '#555',
    },
    '& p span': {
      fontWeight: 'bold',
    },
    '& .weather-type': {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      '& img': {
        marginLeft: '5px',
        width: '24px',
        height: '24px',
      },
    },
  },
  weatherCard: {
    maxWidth: '300px',
    margin: '20px auto',
    padding: '20px',
    backgroundColor: '#f1f1f1',
    border: '1px solid #ddd',
    borderRadius: '8px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    textAlign: 'center',
    fontFamily: 'Arial, sans-serif',
    '& h1': {
      fontSize: '1.8em',
      margin: 0,
      color: '#333',
    },
    '& .left-side': {
      marginTop: '15px',
      '& h3': {
        fontSize: '2.2em',
        color: '#ff8c00',
        margin: 0,
      },
      '& h4': {
        fontSize: '1em',
        color: '#555',
        margin: '5px 0',
      },
      '& p': {
        fontSize: '0.9em',
        color: '#555',
        margin: '8px 0',
      },
      '& p span': {
        fontWeight: 'bold',
      },
      '& .weather-type img': {
        width: '30px',
        height: '30px',
        marginLeft: '5px',
        padding: '5px',
        backgroundColor: '#333',
        borderRadius: '50%',
        boxShadow: '0 2px 4px rgba(0, 0, 0, 0.2)',
      },
    },
  },
  favoritesLink: {
    marginLeft: '20px',
    padding: '8px 12px',
    backgroundColor: '#f7931e',
    color: 'white',
    textDecoration: 'none',
    borderRadius: '4px',
    fontWeight: 'bold',
    fontSize: '1em',
    transition: 'background-color 0.2s ease',
    '&:hover': {
      backgroundColor: '#d9750d',
    },
  },
  favoriteCities: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: '15px',
    padding: '20px',
    maxWidth: '400px',
    margin: '0 auto',
    fontFamily: 'Arial, sans-serif',
    color: '#333',
  },
  favoriteCityItem: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    padding: '10px',
    border: '1px solid #ddd',
    borderRadius: '8px',
    backgroundColor: '#f9f9f9',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
    '& a': {
      textDecoration: 'none',
      color: '#0073e6',
      fontWeight: 'bold',
      fontSize: '1.1em',
      transition: 'color 0.2s ease',
      '&:hover': {
        color: '#004a99',
      },
    },
    '& button': {
      backgroundColor: '#ff4d4f',
      color: 'white',
      border: 'none',
      borderRadius: '4px',
      padding: '5px 10px',
      cursor: 'pointer',
      fontSize: '0.9em',
      transition: 'background-color 0.2s ease',
      '&:hover': {
        backgroundColor: '#cc0000',
      },
    },
  },
  addToFavorites: {
    backgroundColor: '#4caf50',
    color: 'white',
    '&:hover': {
      backgroundColor: '#388e3c',
      transform: 'scale(1.05)',
    },
  },
  removeFromFavorites: {
    backgroundColor: '#ff4d4f',
    color: 'white',
    '&:hover': {
      backgroundColor: '#cc0000',
      transform: 'scale(1.05)',
    },
  },
  favoriteActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    justifyContent: 'center',
    marginTop: '15px',
    '& button': {
      padding: '8px 12px',
      border: 'none',
      borderRadius: '4px',
      cursor: 'pointer',
      fontSize: '0.9em',
      transition: 'background-color 0.2s ease, transform 0.1s ease',
    },
    '& .forecast-link': {
      color: '#0073e6',
      fontWeight: 'bold',
      textDecoration: 'none',
      padding: '8px 12px',
      border: '1px solid #0073e6',
      borderRadius: '4px',
      transition: 'background-color 0.2s ease, color 0.2s ease',
      '&:hover': {
        backgroundColor: '#0073e6',
        color: 'white',
      },
    },
  },
  forecastTemp: {
    color: '#ff8c00',
  },
  timeEntry: {
    borderBottom: '1px solid #ddd',
    paddingBottom: '8px',
    marginBottom: '8px',
  },
  emptyFavorites: {
    textAlign: 'center',
    color: '#888',
    fontSize: '1.1em',
    fontWeight: 500,
    padding: '20px',
    backgroundColor: '#f9f9f9',
    border: '1px solid #ddd',
    borderRadius: '8px',
    margin: '20px auto',
    maxWidth: '300px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.1)',
  },
  loadingSpinner: {
    border: '4px solid #f3f3f3',
    borderTop: '4px solid #0073e6',
    borderRadius: '50%',
    width: '24px',
    height: '24px',
    animation: '$spin 1s linear infinite',
    margin: '5px',
  },
  '@keyframes spin': {
    '0%': { transform: 'rotate(0deg)' },
    '100%': { transform: 'rotate(360deg)' },
  },
  '@media (max-width: 768px)': {
    navbar: {
      flexDirection: 'column',
      alignItems: 'stretch',
      '& input[type="text"], & button, & .favorites-link': {
        width: '100%',
        margin: '5px 0',
      },
    },
    favoriteCities: {
      maxWidth: '100%',
      padding: '15px',
      '& .favorite-city-item': {
        flexDirection: 'column',
        alignItems: 'flex-start',
        '& a, & button': {
          width: '100%',
          textAlign: 'center',
          marginTop: '5px',
        },
      },
    },
  },
};

export default styles;
